[package]
name = "ngs_ir"
version.workspace = true
edition.workspace = true
description = "Intermediate representation and lowering for NagiScript (NGS)"
repository.workspace = true
license.workspace = true
keywords.workspace = true
homepage.workspace = true

[dependencies]
ngs_ast.workspace = true
ngs_sema.workspace = true

[dev-dependencies]
ngs_parser.workspace = true
ngs_lexer.workspace = true
