[package]
name = "ngs_driver"
version.workspace = true
edition.workspace = true
description = "CLI driver for NagiScript (NGS) — check, build, run, wasm, dts, init"
repository.workspace = true
license.workspace = true
keywords.workspace = true
homepage.workspace = true

[[bin]]
name = "nagiscript"
path = "src/main.rs"

[dependencies]
ngs_ast.workspace = true
ngs_lexer.workspace = true
ngs_parser.workspace = true
ngs_sema.workspace = true
ngs_ir.workspace = true
ngs_codegen_llvm.workspace = true
ngs_codegen_wasm.workspace = true
ngs_std.workspace = true
