//! NGS-IR → WebAssembly (WAT テキスト) コード生成 + TypeScript 型定義 (.d.ts) 生成。
//!
//! 設計方針:
//! - 依存クレートなしの WAT テキスト出力。wat2wasm 等で .wasm 化する。
//! - 制御フローは「pc ガードチェーン」方式で任意の CFG を機械的に変換する。
//!   すべての仮想レジスタを wasm ローカルに格下げし、各基本ブロックを
//!   `$pc == ブロック番号` のガード付き if 内に配置する。ブロック終端で
//!   `$pc` を更新してからガードチェーンを抜け、ループ先頭へ戻る。
//! - 集約型（struct/enum/array）を返す関数は LLVM 版と同じ sret 規約
//!   （隠し先頭 i32 引数 = 呼び出し側バッファ、memory.copy で実体を転送）。
//! - メモリ: 先頭に文字列データ + {data:u64,len:u64} セル、以降はグローバル
//!   $heap からのバンプアロケータ。関数脱出時に $heap を復元する
//!   （ループ内の alloca は反復間で再利用されない簡易実装）。
//! - ランタイム (__ngs_* / fmod) は "env" imports として要求し、ホスト(JS 等)が
//!   エクスポートされた memory を介して実装する。List/Rc は生ポインタを
//!   ホストと共有する必要があるため本サブセットでは未対応（明示的エラー）。

use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;

use ngs_ir::{CastKind, Const, Inst, IrBin, IrPred, IrProgram, IrType, Term, V};

#[derive(Debug)]
pub struct CodegenError(pub String);

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl std::error::Error for CodegenError {}

// ---------------------------------------------------------------------------
// 型ユーティリティ
// ---------------------------------------------------------------------------

/// 論理型 → wasm 値型。Str/Ptr/集約はアドレス (i32)。
pub fn wty(t: &IrType) -> &'static str {
    match t {
        IrType::Void => "",
        IrType::F32 => "f32",
        IrType::F64 => "f64",
        IrType::I64 | IrType::U64 | IrType::Usize | IrType::Isize => "i64",
        _ => "i32",
    }
}

pub fn is_signed(t: &IrType) -> bool {
    matches!(t, IrType::I8 | IrType::I16 | IrType::I32 | IrType::I64 | IrType::Isize)
}

fn align16(n: u64) -> u64 {
    n.div_ceil(16) * 16
}

// ---------------------------------------------------------------------------
// ホスト提供シンボル（imports）
// ---------------------------------------------------------------------------

/// (名前, パラメタ型列, 戻り値型("" = void))
pub const IMPORTS: &[(&str, &[&str], &str)] = &[
    ("__ngs_print_str", &["i32", "i32"], ""),
    ("__ngs_println_str", &["i32", "i32"], ""),
    ("__ngs_print_i64", &["i64"], ""),
    ("__ngs_println_i64", &["i64"], ""),
    ("__ngs_print_f64", &["f64"], ""),
    ("__ngs_println_f64", &["f64"], ""),
    ("__ngs_print_bool", &["i32"], ""),
    ("__ngs_println_bool", &["i32"], ""),
    ("__ngs_panic", &["i32", "i32"], ""),
    ("__ngs_abort", &[], ""),
    ("__ngs_str_eq", &["i32", "i32"], "i32"),
    ("__ngs_str_to_i64", &["i32"], "i64"),
    ("__ngs_str_to_f64", &["i32"], "f64"),
    ("__ngs_box_i64", &["i64"], "i64"),
    ("__ngs_box_f64", &["f64"], "i64"),
    ("__ngs_box_bool", &["i32"], "i64"),
    ("__ngs_box_str", &["i32"], "i64"),
    ("__ngs_box_ptr", &["i32"], "i64"),
    ("__ngs_props_new", &[], "i32"),
    ("__ngs_props_tag", &["i32", "i32", "i32"], ""),
    ("__ngs_props_set", &["i32", "i32", "i32", "i64"], ""),
    ("__ngs_props_add_child", &["i32", "i64"], ""),
    ("__ngs_fmod", &["f64", "f64"], "f64"),
];

/// 本サブセットで未対応のランタイム関数
const UNSUPPORTED: &[&str] = &[
    "__ngs_list_new",
    "__ngs_list_push",
    "__ngs_list_len",
    "__ngs_list_at",
    "__ngs_list_free",
    "__ngs_rc_new",
    "__ngs_rc_inc",
    "__ngs_rc_dec",
];

struct ImportSig {
    import_name: String,
    params: Vec<&'static str>,
    ret: &'static str,
}

fn resolve_import(name: &str) -> Option<ImportSig> {
    // lowering は float の剰余を __ngs_fmod 呼び出しとして出力する
    let key = if name == "fmod" { "__ngs_fmod" } else { name };
    if UNSUPPORTED.contains(&key) {
        return None;
    }
    IMPORTS
        .iter()
        .find(|(n, _, _)| *n == key)
        .map(|(n, ps, r)| ImportSig { import_name: n.to_string(), params: ps.to_vec(), ret: r })
}

// ---------------------------------------------------------------------------
// d.ts 生成
// ---------------------------------------------------------------------------

fn ts_type(t: &IrType) -> Option<&'static str> {
    match t {
        IrType::Bool => Some("boolean"),
        IrType::Str => Some("string"),
        IrType::I8 | IrType::I16 | IrType::I32 | IrType::U8 | IrType::U16 | IrType::U32 => Some("number"),
        IrType::I64 | IrType::U64 | IrType::Usize | IrType::Isize => Some("number /* 64-bit */"),
        IrType::F32 | IrType::F64 => Some("number"),
        _ => None,
    }
}

/// C エクスポートから TypeScript 宣言 (.d.ts) を生成する。
pub fn generate_dts(prog: &IrProgram) -> String {
    let mut out = String::new();
    writeln!(out, "// generated by nagiscript (NGS-IR exports -> TypeScript)").ok();
    writeln!(
        out,
        "// Strings cross the boundary as {{ ptr: number, len: number }} views into the exported `memory`."
    )
    .ok();
    writeln!(out).ok();
    for (name, params, ret) in &prog.exports {
        let ps: Vec<String> = params
            .iter()
            .enumerate()
            .map(|(i, (pn, pt))| {
                let pn = if pn.is_empty() { format!("arg{i}") } else { pn.to_string() };
                match ts_type(pt) {
                    Some(t) => format!("{pn}: {t}"),
                    None => format!("/* unsupported type `{}` */ {pn}: never", pt_display(pt)),
                }
            })
            .collect();
        let rt = match ts_type(ret) {
            Some(t) => t.to_string(),
            None => {
                writeln!(
                    out,
                    "// NOTE: `{name}` returns an aggregate/pointer type and cannot be represented in TS."
                )
                .ok();
                "void".to_string()
            }
        };
        writeln!(out, "export function {}({}): {};", name, ps.join(", "), rt).ok();
    }
    out
}

fn pt_display(t: &IrType) -> String {
    match t {
        IrType::Ptr(_) => "*T".to_string(),
        IrType::Array(_, n) => format!("[T; {n}]"),
        IrType::Struct(_) => "struct".to_string(),
        IrType::Enum(_) => "enum".to_string(),
        other => format!("{other:?}"),
    }
}

// ---------------------------------------------------------------------------
// データセグメント
// ---------------------------------------------------------------------------

struct DataSeg {
    bytes: Vec<u8>,
    /// リテラルid → セルオフセット ({data:u64 @0, len:u64 @8}、ネイティブ版と同一)
    cells: Vec<u64>,
}

fn build_data(prog: &IrProgram) -> DataSeg {
    let mut bytes: Vec<u8> = vec![];
    while bytes.len() % 16 != 0 {
        bytes.push(0);
    }
    let mut cells = Vec::with_capacity(prog.strings.len());
    for g in &prog.strings {
        while bytes.len() % 8 != 0 {
            bytes.push(0);
        }
        let data_off = bytes.len() as u64;
        bytes.extend_from_slice(g.content.as_bytes());
        // セル本体 — ネイティブ版と同じ {data: u64, len: u64} レイアウト。
        // lowering は addr_off(+0/+8) で data/len を読むため 16 バイト幅を維持する。
        // （ポインタ値自体は wasm の 32bit 範囲に収まるため u64 にゼロ拡張で格納）
        while bytes.len() % 8 != 0 {
            bytes.push(0);
        }
        let cell_off = bytes.len() as u64;
        bytes.extend_from_slice(&data_off.to_le_bytes());
        bytes.extend_from_slice(&(g.content.len() as u64).to_le_bytes());
        cells.push(cell_off);
    }
    DataSeg { bytes, cells }
}

// ---------------------------------------------------------------------------
// 関数生成
// ---------------------------------------------------------------------------

enum Callee {
    /// prog.funcs のインデックス
    Local(usize),
    Import(ImportSig),
}

struct FnGen<'a> {
    prog: &'a IrProgram,
    seg: &'a DataSeg,
    f: &'a ngs_ir::IrFunction,
    out: String,
    ind: usize,
    /// V id -> 論理型（pass1 推論結果）
    tys: HashMap<V, IrType>,
    /// V id -> ローカル番号
    local_of: HashMap<V, usize>,
    n_locals: usize,
    sret_local: Option<usize>,
    frame_local: usize,
    pc_local: usize,
    scratch: usize,
    /// CheckedBin(Mul) の 64bit 中間値用スクラッチ
    wide_local: usize,
}

/// pass1: 各 V の論理型を推定（LLVM 版の bind 規則と同一）
fn infer_tys(prog: &IrProgram, f: &ngs_ir::IrFunction) -> HashMap<V, IrType> {
    let mut tys = HashMap::new();
    for (i, (_, t)) in f.params.iter().enumerate() {
        tys.insert(i, t.clone());
    }
    for b in &f.blocks {
        for inst in &b.insts {
            match inst {
                Inst::Const { dst, val } => {
                    let t = match val {
                        Const::Int(_) => IrType::I64,
                        Const::Float(_) => IrType::F64,
                        Const::Bool(_) => IrType::Bool,
                        Const::Str(_) => IrType::Str,
                        Const::NullPtr => IrType::Ptr(std::rc::Rc::new(IrType::U8)),
                    };
                    tys.insert(*dst, t);
                }
                Inst::Alloca { dst, .. } => {
                    // alloca の結果は「セルのアドレス」（wasm では i32）
                    tys.insert(*dst, IrType::Ptr(std::rc::Rc::new(IrType::U8)));
                }
                Inst::Load { dst, ty, .. } => {
                    tys.insert(*dst, ty.clone());
                }
                Inst::BinOp { dst, ty, .. } => {
                    tys.insert(*dst, ty.clone());
                }
                Inst::CmpOp { dst, .. } => {
                    tys.insert(*dst, IrType::Bool);
                }
                Inst::CheckedBin { dst_val, dst_ovf, ty, .. } => {
                    tys.insert(*dst_val, ty.clone());
                    tys.insert(*dst_ovf, IrType::Bool);
                }
                Inst::Call { dst: Some(dst), ret, .. } => {
                    tys.insert(*dst, ret.clone());
                }
                Inst::FieldAddr { dst, .. }
                | Inst::ElemAddr { dst, .. }
                | Inst::AddrOff { dst, .. } => {
                    tys.insert(*dst, IrType::Ptr(std::rc::Rc::new(IrType::U8)));
                }
                Inst::Cast { dst, to, .. } | Inst::Bitcast { dst, to, .. } => {
                    tys.insert(*dst, to.clone());
                }
                Inst::BoxVal { dst, .. } => {
                    tys.insert(*dst, IrType::I64);
                }
                Inst::Store { .. }
                | Inst::CopyAgg { .. }
                | Inst::RcInc { .. }
                | Inst::RcDec { .. }
                | Inst::Call { dst: None, .. } => {}
            }
        }
    }
    let _ = prog;
    tys
}

impl<'a> FnGen<'a> {
    fn w(&mut self, s: &str) {
        writeln!(self.out, "{}{s}", "  ".repeat(self.ind)).ok();
    }

    fn ty_of(&self, v: V) -> IrType {
        self.tys.get(&v).cloned().unwrap_or(IrType::I64)
    }

    /// V の値をスタックへ積む（変換なし・生のまま）
    fn push_val(&mut self, v: V) {
        let l = self.local_of[&v];
        self.w(&format!("local.get {l}"));
    }

    /// スタックトップの生値を from 論理型から to 論理型の表現へ変換する
    fn conv(&mut self, from: &IrType, to: &IrType, signed_hint: Option<bool>) {
        let wf = wty(from);
        let wt = wty(to);
        if wf == wt {
            return;
        }
        let sg = signed_hint.unwrap_or_else(|| is_signed(from));
        match (wf, wt) {
            ("i32", "i64") => {
                if sg {
                    self.w("i64.extend_i32_s");
                } else {
                    self.w("i64.extend_i32_u");
                }
            }
            ("i64", "i32") => self.w("i32.wrap_i64"),
            ("i32", "f32") => {
                if sg {
                    self.w("f32.convert_i32_s");
                } else {
                    self.w("f32.convert_i32_u");
                }
            }
            ("i32", "f64") => {
                if sg {
                    self.w("f64.convert_i32_s");
                } else {
                    self.w("f64.convert_i32_u");
                }
            }
            ("i64", "f32") => {
                if sg {
                    self.w("f32.convert_i64_s");
                } else {
                    self.w("f32.convert_i64_u");
                }
            }
            ("i64", "f64") => {
                if sg {
                    self.w("f64.convert_i64_s");
                } else {
                    self.w("f64.convert_i64_u");
                }
            }
            ("f32", "i32") => {
                if sg {
                    self.w("i32.trunc_f32_s");
                } else {
                    self.w("i32.trunc_f32_u");
                }
            }
            ("f64", "i32") => {
                if sg {
                    self.w("i32.trunc_f64_s");
                } else {
                    self.w("i32.trunc_f64_u");
                }
            }
            ("f32", "i64") => {
                if sg {
                    self.w("i64.trunc_f32_s");
                } else {
                    self.w("i64.trunc_f32_u");
                }
            }
            ("f64", "i64") => {
                if sg {
                    self.w("i64.trunc_f64_s");
                } else {
                    self.w("i64.trunc_f64_u");
                }
            }
            ("f32", "f64") => self.w("f64.promote_f32"),
            ("f64", "f32") => self.w("f32.demote_f64"),
            _ => {
                // 同一スロット幅（ptr↔整数など）は何もしない
            }
        }
    }

    /// 値 v を want（wasm 型）の表現へ強制する
    fn coerce_arg(&mut self, v: V, want: &str) {
        let lt = self.ty_of(v);
        let cur = wty(&lt);
        if cur == want {
            self.push_val(v);
            return;
        }
        self.push_val(v);
        let dummy = match want {
            "i64" => IrType::I64,
            "f32" => IrType::F32,
            "f64" => IrType::F64,
            _ => IrType::I32,
        };
        self.conv(&lt, &dummy, None);
    }

    /// バンプアロケーション（align16）。確保したアドレスをスタックに積む。
    fn emit_bump(&mut self, size: u64) {
        let sz = align16(size.max(1));
        self.w("global.get $heap");
        self.w("global.get $heap");
        self.w(&format!("i32.const {sz}"));
        self.w("i32.add");
        self.w("global.set $heap");
        // スタックには旧 $heap（= 確保アドレス）が残る
    }

    fn restore_heap(&mut self) {
        self.w(&format!("local.get {}", self.frame_local));
        self.w("global.set $heap");
    }

    fn gen_function(&mut self) -> Result<(), CodegenError> {
        let f = self.f;
        // フレーム保存（バンプポインタ復元用）
        self.w("global.get $heap");
        self.w(&format!("local.set {}", self.frame_local));

        // ガードチェーン
        let nb = f.blocks.len();
        self.w("loop $top");
        self.ind += 1;
        self.w("block $next");
        self.ind += 1;
        for (bi, block) in f.blocks.iter().enumerate() {
            if bi == 0 {
                self.w(&format!("local.get {}", self.pc_local));
                self.w("i32.eqz");
            } else {
                self.w(&format!("local.get {}", self.pc_local));
                self.w(&format!("i32.const {bi}"));
                self.w("i32.eq");
            }
            self.w("if");
            self.ind += 1;
            self.w(&format!(";; block {} (pc={bi})", block.label));
            for inst in &block.insts {
                self.gen_inst(inst)?;
            }
            self.gen_term(&block.term)?;
            self.ind -= 1;
            self.w("end");
        }
        self.w(";; 不正な pc は到達不能");
        self.w("unreachable");
        self.ind -= 1;
        self.w("end ;; $next");
        self.w("br 0 ;; $top");
        self.ind -= 1;
        self.w("end ;; $top");
        self.w("unreachable ;; ループは必ず return で抜ける");
        self.w(") ;; func");
        Ok(())
    }

    fn gen_term(&mut self, term: &Term) -> Result<(), CodegenError> {
        match term {
            Term::Ret(None) => {
                self.restore_heap();
                self.w("return");
            }
            Term::Ret(Some(v)) => {
                let vt = self.ty_of(*v);
                if self.f.ret.is_aggregate() {
                    // sret バッファへ実体を転送してから返る
                    let sl = self.sret_local.expect("sret param");
                    let sz = self.prog.size_of(&self.f.ret);
                    self.w(&format!("local.get {sl}"));
                    self.push_val(*v);
                    self.w(&format!("i32.const {sz}"));
                    self.w("memory.copy");
                } else {
                    self.push_val(*v);
                    self.conv(&vt, &self.f.ret, None);
                }
                self.restore_heap();
                self.w("return");
            }
            Term::Br(l) => {
                let idx = self.f.find_block(l).ok_or_else(|| CodegenError(format!("unknown block `{l}`")))?;
                self.w(&format!("i32.const {idx}"));
                self.w(&format!("local.set {}", self.pc_local));
                self.w("br 1 ;; $next");
            }
            Term::CondBr(c, t_label, f_label) => {
                let ti =
                    self.f.find_block(t_label).ok_or_else(|| CodegenError(format!("unknown block `{t_label}`")))?;
                let fi =
                    self.f.find_block(f_label).ok_or_else(|| CodegenError(format!("unknown block `{f_label}`")))?;
                self.push_val(*c);
                self.w("if");
                self.w(&format!("  i32.const {ti}"));
                self.w(&format!("  local.set {}", self.pc_local));
                self.w("else");
                self.w(&format!("  i32.const {fi}"));
                self.w(&format!("  local.set {}", self.pc_local));
                self.w("end");
                self.w("br 1 ;; $next");
            }
            Term::Unreachable => {
                self.w("unreachable");
            }
        }
        Ok(())
    }

    // --- 命令 ---

    fn load_op(t: &IrType) -> &'static str {
        match t {
            IrType::Bool | IrType::I8 | IrType::U8 => "i32.load8_u",
            IrType::I16 | IrType::U16 => "i32.load16_u",
            IrType::F32 => "f32.load",
            IrType::F64 => "f64.load",
            IrType::I64 | IrType::U64 | IrType::Usize | IrType::Isize => "i64.load",
            _ => "i32.load", // i32/u32/ptr/str/集約セル
        }
    }

    fn store_op(t: &IrType) -> &'static str {
        match t {
            IrType::Bool | IrType::I8 | IrType::U8 => "i32.store8",
            IrType::I16 | IrType::U16 => "i32.store16",
            IrType::F32 => "f32.store",
            IrType::F64 => "f64.store",
            IrType::I64 | IrType::U64 | IrType::Usize | IrType::Isize => "i64.store",
            _ => "i32.store",
        }
    }

    fn resolve_callee(&self, name: &str) -> Result<Callee, CodegenError> {
        if let Some(idx) = self.prog.funcs.iter().position(|f| f.name == name && !f.blocks.is_empty()) {
            return Ok(Callee::Local(idx));
        }
        match resolve_import(name) {
            Some(sig) => Ok(Callee::Import(sig)),
            None => Err(CodegenError(format!(
                "`{name}` cannot be called from wasm output (List/Rc intrinsics are not supported by the wasm backend yet)"
            ))),
        }
    }

    fn callee_param_tys(prog: &IrProgram, idx: usize) -> Vec<IrType> {
        prog.funcs[idx].params.iter().map(|(_, t)| t.clone()).collect()
    }

    fn gen_inst(&mut self, inst: &Inst) -> Result<(), CodegenError> {
        match inst {
            Inst::Const { dst, val } => {
                match val {
                    Const::Int(n) => self.w(&format!("i64.const {n}")),
                    Const::Float(x) => {
                        self.w(&format!("i64.const {}", x.to_bits()));
                        self.w("f64.reinterpret_i64");
                    }
                    Const::Bool(b) => self.w(&format!("i32.const {}", if *b { 1 } else { 0 })),
                    Const::Str(id) => {
                        let off = *self.seg.cells.get(*id as usize).ok_or_else(|| {
                            CodegenError(format!("string literal id {id} not found"))
                        })?;
                        self.w(&format!("i32.const {off}"));
                    }
                    Const::NullPtr => self.w("i32.const 0"),
                }
                self.set_local(*dst);
            }
            Inst::Alloca { dst, ty } => {
                let sz = self.prog.size_of(ty);
                self.emit_bump(sz);
                self.set_local(*dst);
            }
            Inst::Load { dst, addr, ty } => {
                self.push_val(*addr);
                self.w(Self::load_op(ty));
                self.set_local(*dst);
            }
            Inst::Store { addr, val, ty } => {
                self.push_val(*addr);
                let lt = self.ty_of(*val);
                self.push_val(*val);
                self.conv(&lt, ty, None);
                self.w(Self::store_op(ty));
            }
            Inst::BinOp { dst, op, ty, a, b } => {
                let at = self.ty_of(*a);
                let bt = self.ty_of(*b);
                self.push_val(*a);
                self.conv(&at, ty, None);
                self.push_val(*b);
                self.conv(&bt, ty, None);
                if ty.is_float() {
                    let mop = match op {
                        IrBin::Add => "add",
                        IrBin::Sub => "sub",
                        IrBin::Mul => "mul",
                        IrBin::Div => "div",
                        IrBin::Mod => {
                            // wasm に剰余命令はないためホストの fmod を利用
                            let pre = matches!(wty(ty), "f32");
                            if pre {
                                self.conv(ty, &IrType::F64, None);
                                self.conv(ty, &IrType::F64, None);
                            }
                            self.w("call $__ngs_fmod");
                            if pre {
                                self.conv(&IrType::F64, ty, None);
                            }
                            self.set_local(*dst);
                            return Ok(());
                        }
                    };
                    let p = wty(ty);
                    self.w(&format!("{p}.{mop}"));
                } else {
                    let s = if is_signed(ty) { "s" } else { "u" };
                    let p = wty(ty);
                    let mop: String = match op {
                        IrBin::Add => "add".into(),
                        IrBin::Sub => "sub".into(),
                        IrBin::Mul => "mul".into(),
                        IrBin::Div => format!("div_{s}"),
                        IrBin::Mod => format!("rem_{s}"),
                    };
                    self.w(&format!("{p}.{mop}"));
                }
                self.set_local(*dst);
            }
            Inst::CmpOp { dst, pred, ty, a, b } => {
                let at = self.ty_of(*a);
                let bt = self.ty_of(*b);
                self.push_val(*a);
                self.conv(&at, ty, None);
                self.push_val(*b);
                self.conv(&bt, ty, None);
                let p = wty(ty);
                let sop = match pred {
                    IrPred::Eq => "eq",
                    IrPred::Ne => "ne",
                    IrPred::Lt => "lt",
                    IrPred::Le => "le",
                    IrPred::Gt => "gt",
                    IrPred::Ge => "ge",
                };
                let op = if ty.is_float() {
                    format!("{p}.{sop}")
                } else {
                    match pred {
                        IrPred::Eq | IrPred::Ne => format!("{p}.{sop}"),
                        _ => {
                            let s = if is_signed(ty) { "s" } else { "u" };
                            format!("{p}.{sop}_{s}")
                        }
                    }
                };
                self.w(&op);
                self.set_local(*dst);
            }
            Inst::CheckedBin { dst_val, dst_ovf, op, ty, a, b } => {
                self.gen_checked_bin(*dst_val, *dst_ovf, *op, ty, *a, *b)?;
            }
            Inst::Call { dst, func, args, ret } => {
                self.gen_call(dst.as_ref().filter(|d| **d != ngs_ir::NO_V), func, args, ret)?;
            }
            Inst::FieldAddr { dst, base, struct_id, field } => {
                let off = self.prog.field_offset(*struct_id, *field);
                self.push_val(*base);
                self.w(&format!("i32.const {off}"));
                self.w("i32.add");
                self.set_local(*dst);
            }
            Inst::ElemAddr { dst, base, index, elem } => {
                let stride = self.prog.cell_of(elem);
                let it = self.ty_of(*index);
                self.push_val(*base);
                self.push_val(*index);
                self.conv(&it, &IrType::I32, None);
                self.w(&format!("i32.const {stride}"));
                self.w("i32.mul");
                self.w("i32.add");
                self.set_local(*dst);
            }
            Inst::AddrOff { dst, base, off } => {
                self.push_val(*base);
                self.w(&format!("i32.const {off}"));
                self.w("i32.add");
                self.set_local(*dst);
            }
            Inst::Cast { dst, kind, val, to } => {
                let from = self.ty_of(*val);
                self.push_val(*val);
                self.gen_cast(*kind, &from, to)?;
                self.set_local(*dst);
            }
            Inst::Bitcast { dst, val, to } => {
                let from = self.ty_of(*val);
                self.push_val(*val);
                self.conv(&from, to, None);
                self.set_local(*dst);
            }
            Inst::CopyAgg { dst_addr, src_ptr, ty } => {
                let sz = self.prog.size_of(ty);
                self.push_val(*dst_addr);
                self.push_val(*src_ptr);
                self.w(&format!("i32.const {sz}"));
                self.w("memory.copy");
            }
            Inst::RcInc { .. } | Inst::RcDec { .. } => {
                return Err(CodegenError(
                    "List/Rc are not supported by the wasm backend yet".into(),
                ));
            }
            Inst::BoxVal { dst, src, ty } => {
                let st = self.ty_of(*src);
                let (imp, argt) = match ty {
                    IrType::Bool => ("__ngs_box_bool", IrType::Bool),
                    IrType::F32 | IrType::F64 => ("__ngs_box_f64", IrType::F64),
                    IrType::Str => ("__ngs_box_str", IrType::Str),
                    t if t.is_int() => ("__ngs_box_i64", IrType::I64),
                    _ => ("__ngs_box_ptr", IrType::Ptr(std::rc::Rc::new(IrType::U8))),
                };
                self.push_val(*src);
                self.conv(&st, &argt, None);
                self.w(&format!("call ${imp}"));
                self.set_local(*dst);
            }
        }
        Ok(())
    }

    fn set_local(&mut self, v: V) {
        let l = self.local_of[&v];
        self.w(&format!("local.set {l}"));
    }

    fn gen_checked_bin(
        &mut self,
        dst_val: V,
        dst_ovf: V,
        op: IrBin,
        ty: &IrType,
        a: V,
        b: V,
    ) -> Result<(), CodegenError> {
        let sg = is_signed(ty);
        let at = self.ty_of(a);
        let bt = self.ty_of(b);
        let p = wty(ty);
        let bits = ty.bits();

        if op == IrBin::Mul && bits == 64 {
            return Err(CodegenError(
                "checked multiplication of 64-bit integers is not supported by the wasm backend yet".into(),
            ));
        }

        match op {
            IrBin::Add | IrBin::Sub => {
                self.push_val(a);
                self.conv(&at, ty, None);
                self.push_val(b);
                self.conv(&bt, ty, None);
                let base_op = if op == IrBin::Add { "add" } else { "sub" };
                self.w(&format!("{p}.{base_op}"));
                // 桁落ち検出のための準備: r を保存しておく
                let rv = self.local_of[&dst_val];
                self.w(&format!("local.set {rv}"));
                // ovf 計算（オペランドは必ず変換済みの値を積み直す。
                // ローカルには Const::Int 等の生表現が入っているため直接読むと幅が合わない）
                //   符号付き add: ((a^r)&(b^r))<0 / sub: ((a^b)&(a^r))<0
                //   符号なし add: r<a / sub: a<b （ともに unsigned比較）
                if sg {
                    let push_coerced = |g: &mut Self, v: V| {
                        let lt = g.ty_of(v);
                        g.push_val(v);
                        g.conv(&lt, ty, None);
                    };
                    // a ^ (b | r 側)
                    push_coerced(self, a);
                    if op == IrBin::Add {
                        self.w(&format!("local.get {rv}"));
                    } else {
                        push_coerced(self, b);
                    }
                    self.w(&format!("{p}.xor"));
                    if op == IrBin::Add {
                        push_coerced(self, b);
                        self.w(&format!("local.get {rv}"));
                    } else {
                        push_coerced(self, a);
                        self.w(&format!("local.get {rv}"));
                    }
                    self.w(&format!("{p}.xor"));
                    self.w(&format!("{p}.and"));
                    self.w(&format!("{p}.const 0"));
                    self.w(&format!("{p}.lt_s"));
                } else if op == IrBin::Add {
                    self.w(&format!("local.get {rv}"));
                    let lt = self.ty_of(a);
                    self.push_val(a);
                    self.conv(&lt, ty, None);
                    self.w(&format!("{p}.lt_u"));
                } else {
                    let lta = self.ty_of(a);
                    self.push_val(a);
                    self.conv(&lta, ty, None);
                    let ltb = self.ty_of(b);
                    self.push_val(b);
                    self.conv(&ltb, ty, None);
                    self.w(&format!("{p}.lt_u"));
                }
                self.set_local(dst_ovf);
            }
            IrBin::Mul => {
                // 32bit のみ: i64 へ拡張して乗算し、上位ビットで桁落ち判定
                let wide = IrType::I64;
                self.push_val(a);
                self.conv(&at, &wide, Some(sg));
                self.push_val(b);
                self.conv(&bt, &wide, Some(sg));
                self.w("i64.mul");
                let tl = self.wide_local;
                self.w(&format!("local.set {tl}"));
                // fits = (t << 32 >>s 32) == t
                self.w(&format!("local.get {tl}"));
                self.w("i64.const 32");
                self.w("i64.shl");
                self.w("i64.const 32");
                if sg {
                    self.w("i64.shr_s");
                } else {
                    self.w("i64.shr_u");
                }
                self.w(&format!("local.get {tl}"));
                self.w("i64.ne");
                self.set_local(dst_ovf);
                // 結果を 32bit へ切り詰め
                self.w(&format!("local.get {tl}"));
                self.w("i32.wrap_i64");
                self.set_local(dst_val);
            }
            _ => unreachable!(),
        }
        Ok(())
    }

    fn gen_call(
        &mut self,
        dst: Option<&V>,
        func: &str,
        args: &[V],
        ret: &IrType,
    ) -> Result<(), CodegenError> {
        match self.resolve_callee(func)? {
            Callee::Local(idx) => {
                let sret = ret.is_aggregate();
                let mut buf_addr: Option<usize> = None;
                if sret {
                    let sz = self.prog.size_of(ret);
                    self.emit_bump(sz);
                    let l = self.scratch;
                    self.w(&format!("local.set {l}"));
                    buf_addr = Some(l);
                }
                if sret {
                    self.w(&format!("local.get {}", buf_addr.unwrap()));
                }
                let ptys = Self::callee_param_tys(self.prog, idx);
                for (i, a) in args.iter().enumerate() {
                    match ptys.get(i) {
                        Some(pt) => {
                            let lt = self.ty_of(*a);
                            self.push_val(*a);
                            self.conv(&lt, pt, None);
                        }
                        None => self.coerce_arg(*a, "i32"),
                    }
                }
                let sym = sanitize_name(&self.prog.funcs[idx].name);
                self.w(&format!("call ${sym}"));
                if let Some(d) = dst {
                    if sret {
                        self.w(&format!("local.get {}", buf_addr.unwrap()));
                    }
                    self.set_local(*d);
                } else if !sret && !matches!(ret, IrType::Void) {
                    // 破棄される戻り値はスタックから落とす
                    self.w("drop");
                }
            }
            Callee::Import(sig) => {
                for (i, a) in args.iter().enumerate() {
                    let want = sig.params.get(i).copied().unwrap_or("i32");
                    self.coerce_arg(*a, want);
                }
                let sym = sanitize_import_sym(&sig.import_name);
                self.w(&format!("call ${sym}"));
                if let Some(d) = dst {
                    self.set_local(*d);
                } else if !sig.ret.is_empty() {
                    self.w("drop");
                }
            }
        }
        Ok(())
    }

    /// Cast 命令の意味論を反映した変換（値はスタック上）
    fn gen_cast(&mut self, kind: CastKind, from: &IrType, to: &IrType) -> Result<(), CodegenError> {
        match kind {
            CastKind::Trunc => {
                // 64bit スロットならまず wrap
                if wty(from) == "i64" && wty(to) == "i32" {
                    self.w("i32.wrap_i64");
                }
                // 目標幅 < 32bit なら正規化（符号なし: マスク / 符号あり: シフトで符号拡張）
                let b = to.bits();
                if b < 32 {
                    let sh = 32 - b;
                    if is_signed(to) {
                        self.w(&format!("i32.const {sh}"));
                        self.w("i32.shl");
                        self.w(&format!("i32.const {sh}"));
                        self.w("i32.shr_s");
                    } else {
                        let mask = (1u64 << b) - 1;
                        self.w(&format!("i32.const {mask}"));
                        self.w("i32.and");
                    }
                }
            }
            CastKind::Zext | CastKind::Sext => {
                let sg = kind == CastKind::Sext;
                self.conv(from, to, Some(sg));
            }
            CastKind::Sitofp => self.conv(from, to, Some(true)),
            CastKind::Fptosi => self.conv(from, to, Some(true)),
            CastKind::Fptoui => self.conv(from, to, Some(false)),
            CastKind::Fpext | CastKind::Fptrunc => self.conv(from, to, None),
            CastKind::Inttoptr | CastKind::Ptrtoint | CastKind::BoolToInt => self.conv(from, to, None),
            CastKind::IntToBool => {
                // x != 0 を 0/1 へ正規化
                let p = wty(from);
                self.w(&format!("{p}.eqz"));
                self.w("i32.eqz");
                let _ = p;
            }
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// 名前処理
// ---------------------------------------------------------------------------

fn sanitize_name(name: &str) -> String {
    let ok = name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if ok {
        format!("{name}")
    } else {
        format!("f{}", crc(name))
    }
}

fn sanitize_import_sym(import_name: &str) -> String {
    // import はその名前で宣言されているため同一のサニタイズを適用する
    sanitize_name(import_name)
}

fn crc(s: &str) -> u64 {
    let mut h = 5381u64;
    for b in s.bytes() {
        h = h.wrapping_mul(33).wrapping_add(b as u64);
    }
    h & 0xFFFFF
}

// ---------------------------------------------------------------------------
// エントリポイント
// ---------------------------------------------------------------------------

/// NGS-IR プログラム全体を WAT テキストへ変換する。
pub fn generate_wat(prog: &IrProgram) -> Result<String, CodegenError> {
    // 未対応ランタイム参照を早期検出
    for f in &prog.funcs {
        for b in &f.blocks {
            for i in &b.insts {
                if let Inst::Call { func, .. } = i {
                    if UNSUPPORTED.contains(&func.as_str()) {
                        return Err(CodegenError(format!(
                            "`{func}` is not supported by the wasm backend (List/Rc require shared native pointers)"
                        )));
                    }
                }
            }
        }
    }

    let seg = build_data(prog);
    let heap_base = align16(seg.bytes.len() as u64).max(16);
    let pages = (heap_base / 65536) + 2;

    let mut out = String::new();
    writeln!(out, "(module").ok();
    writeln!(out, "  ;; generated by nagiscript (NGS-IR -> WAT)").ok();
    writeln!(out, "  ;; runtime functions must be provided by the host via env imports").ok();

    for (name, ps, r) in IMPORTS {
        let psig = ps.iter().map(|p| format!("(param {p})")).collect::<Vec<_>>().join(" ");
        let rsig = if r.is_empty() { String::new() } else { format!(" (result {r})") };
        writeln!(out, "  (import \"env\" \"{name}\" (func ${name} {psig}{rsig}))").ok();
    }

    writeln!(out, "  (memory (export \"memory\") {pages})").ok();
    writeln!(out, "  (global $heap (mut i32) (i32.const {heap_base}))").ok();

    if !seg.bytes.is_empty() {
        let mut hex = String::with_capacity(seg.bytes.len() * 4);
        for b in &seg.bytes {
            write!(hex, "\\{:02x}", b).ok();
        }
        writeln!(out, "  (data (i32.const 0) \"{hex}\")").ok();
    }

    for f in &prog.funcs {
        if f.blocks.is_empty() {
            continue;
        }
        let tys = infer_tys(prog, f);

        // ローカル割当: [sret] params... | V ids | frame | pc | scratch
        let mut local_of = HashMap::new();
        let mut n_locals = 0usize;
        let mut param_wtys: Vec<&'static str> = Vec::new();
        let sret_local = if f.ret.is_aggregate() {
            let l = n_locals;
            n_locals += 1;
            param_wtys.push("i32");
            Some(l)
        } else {
            None
        };
        for (i, (_, t)) in f.params.iter().enumerate() {
            local_of.insert(i, n_locals);
            n_locals += 1;
            param_wtys.push(wty(t));
        }
        let max_v = tys.keys().copied().max().map(|m| m + 1).unwrap_or(0).max(f.params.len());
        for v in 0..max_v {
            local_of.entry(v).or_insert_with(|| {
                let l = n_locals;
                n_locals += 1;
                l
            });
        }
        let frame_local = n_locals;
        n_locals += 1;
        let pc_local = n_locals;
        n_locals += 1;
        let scratch = n_locals;
        n_locals += 1;
        let wide_local = n_locals;
        n_locals += 1;
        // ローカル宣言（パラメタ分を除く）を型ごとにグルーピング
        let mut inv: HashMap<usize, IrType> = HashMap::new();
        for (v, l) in &local_of {
            if *l >= f.params.len() + if sret_local.is_some() { 1 } else { 0 } {
                inv.insert(*l, tys.get(v).cloned().unwrap_or(IrType::I64));
            }
        }
        inv.insert(wide_local, IrType::I64);
        // ローカルは位置が意味を持つため、同じ型の「連続区間」ごとに宣言する
        let base = f.params.len() + if sret_local.is_some() { 1 } else { 0 };
        let mut runs: Vec<(&'static str, usize)> = vec![];
        for l in base..n_locals {
            let t = wty(&inv.get(&l).cloned().unwrap_or(IrType::I32));
            match runs.last_mut() {
                Some(last) if last.0 == t => last.1 += 1,
                _ => runs.push((t, 1)),
            }
        }
        let mut locals_decl = String::new();
        for (t, n) in runs {
            let items: Vec<&str> = vec![t; n];
            write!(locals_decl, "(local {}) ", items.join(" ")).ok();
        }

        let mut g = FnGen {
            prog,
            seg: &seg,
            f,
            out: String::new(),
            ind: 0,
            tys,
            local_of,
            n_locals,
            sret_local,
            frame_local,
            pc_local,
            scratch,
            wide_local,
        };
        g.out = String::new();
        // シグネチャ行
        let fname = sanitize_name(&f.name);
        let mut sig = format!("(func ${fname}");
        for t in &param_wtys {
            write!(sig, " (param {t})").ok();
        }
        if !f.ret.is_aggregate() && !matches!(f.ret, IrType::Void) {
            write!(sig, " (result {})", wty(&f.ret)).ok();
        }
        writeln!(g.out, "{sig} {locals_decl}").ok();
        g.ind = 1;
        g.gen_function()?;
        out.push_str(&g.out);
        out.push('\n');
    }

    // エクスポート（シグネチャ一致で C-ABI 定義に対応付け）
    let mut used: HashSet<String> = HashSet::new();
    for (ename, eparams, eret) in &prog.exports {
        let mut found: Option<&ngs_ir::IrFunction> = None;
        for f in &prog.funcs {
            if f.blocks.is_empty() || !f.cconv_c || used.contains(&f.name) {
                continue;
            }
            let psame = eparams.len() == f.params.len()
                && eparams.iter().zip(f.params.iter()).all(|((_, ta), (_, tb))| wty(ta) == wty(tb));
            let rsame = match (eret.is_aggregate(), f.ret.is_aggregate()) {
                (true, true) => true,
                (false, false) => wty(eret) == wty(&f.ret),
                _ => false,
            };
            if psame && rsame {
                found = Some(f);
                break;
            }
        }
        match found {
            Some(f) => {
                used.insert(f.name.clone());
                writeln!(out, "  (export \"{ename}\" (func ${}))", sanitize_name(&f.name)).ok();
            }
            None => {
                return Err(CodegenError(format!("export `{ename}` has no matching wasm definition")));
            }
        }
    }
    if let Some(mn) = &prog.main_name {
        let mf = prog
            .funcs
            .iter()
            .find(|f| &f.name == mn && !f.blocks.is_empty())
            .ok_or_else(|| CodegenError(format!("main function `{mn}` not found")))?;
        writeln!(out, "  (export \"main\" (func ${}))", sanitize_name(mn)).ok();
    }

    writeln!(out, ")").ok();
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use ngs_ir::FnBuilder;

    fn hello_program() -> IrProgram {
        // fn main() { println("hi"); let x = 40 + 2; print(x) } 相当を手組み
        // （print_str は lowering と同様にセルからの {data,len} 読み出しを伴う 2 引数呼び出し）
        let mut b = FnBuilder::new("__NGS_main".into(), vec![], IrType::Void, false);
        let msg = b.str_lit("hi");
        let dp = b.addr_off(msg, 0);
        let lp = b.addr_off(msg, 8);
        let d = b.load(dp, IrType::Ptr(std::rc::Rc::new(IrType::U8)));
        let l = b.load(lp, IrType::Usize);
        b.call("__ngs_println_str", vec![d, l], IrType::Void);
        let a = b.const_int(40);
        let c = b.const_int(2);
        let s = b.binop(IrBin::Add, IrType::I64, a, c);
        b.call("__ngs_println_i64", vec![s], IrType::Void);
        b.ret(None);
        IrProgram {
            funcs: vec![b.func],
            strings: b.strings.iter().map(|s| ngs_ir::GlobalString { content: s.clone() }).collect(),
            main_name: Some("__NGS_main".into()),
            ..Default::default()
        }
    }

    #[test]
    fn wat_generates_and_validates_structure() {
        let prog = hello_program();
        let wat = generate_wat(&prog).expect("generate_wat");
        assert!(wat.contains("(module"));
        assert!(wat.contains("import \"env\" \"__ngs_println_str\""));
        assert!(wat.contains("(data (i32.const 0)"));
        assert!(wat.contains("export \"main\""));
        // バランス確認: (module に対して ) が対応
        let opens = wat.matches('(').count();
        let closes = wat.matches(')').count();
        assert_eq!(opens, closes);
    }

    #[test]
    fn wat_rejects_list_intrinsics() {
        let mut b = FnBuilder::new("__NGS_main".into(), vec![], IrType::Void, false);
        let arg = b.const_int(8);
        b.call("__ngs_list_new", vec![arg], IrType::Ptr(std::rc::Rc::new(IrType::U8)));
        b.ret(None);
        let prog = IrProgram {
            funcs: vec![b.func],
            strings: vec![],
            main_name: Some("__NGS_main".into()),
            ..Default::default()
        };
        let err = generate_wat(&prog).unwrap_err();
        assert!(err.0.contains("not supported"), "{}", err.0);
    }

    #[test]
    fn dts_lists_exports() {
        let prog = IrProgram {
            exports: vec![(
                "add".into(),
                vec![("a".into(), IrType::I32), ("b".into(), IrType::I32)],
                IrType::I32,
            )],
            ..Default::default()
        };
        let dts = generate_dts(&prog);
        assert!(dts.contains("export function add(a: number, b: number): number;"));
    }

    #[test]
    fn wat2wasm_accepts_output_when_available() {
        let prog = full_feature_program();
        let wat = generate_wat(&prog).expect("generate_wat");
        let dir = std::env::temp_dir().join("ngs_wat_test");
        std::fs::create_dir_all(&dir).ok();
        let wat_path = dir.join("test.wat");
        std::fs::write(&wat_path, &wat).expect("write wat");

        if std::process::Command::new("wat2wasm").arg("--version").output().is_err() {
            // ツールが無い環境ではスキップ
            return;
        }
        let wasm_path = dir.join("test.wasm");
        let out = std::process::Command::new("wat2wasm")
            .args([wat_path.to_str().unwrap(), "-o", wasm_path.to_str().unwrap()])
            .output()
            .expect("run wat2wasm");
        assert!(
            out.status.success(),
            "wat2wasm failed:\n{}\n--- WAT ---\n{wat}",
            String::from_utf8_lossy(&out.stderr)
        );
    }

    /// 分岐・ループ・構造体(sret)・文字列・checked bin・cast を網羅する手組みプログラム
    fn full_feature_program() -> IrProgram {
        // struct Point { x:i32, y:i32 }  (sid 0)
        // fn area(p: Point) -> i32 { p.x * p.y }        ← checked mul (i32)
        // fn make() -> Point { Point{x:3,y:7} }         ← sret
        // fn main() { let p = make(); let a = area(p); print(if a > 10 {"big"} else {"small"}) }
        let structs = vec![ngs_ir::IrStruct {
            mangled: "Point".into(),
            fields: vec![("x".into(), IrType::I32), ("y".into(), IrType::I32)],
            is_list: false,
        }];

        // area(p: ptr(Point)) -> i32
        let mut area =
            FnBuilder::new("_NGS_area".into(), vec![("p".into(), IrType::Struct(0))], IrType::I32, true);
        let px = area.field_addr(0, 0, 0);
        let xv = area.load(px, IrType::I32);
        let py = area.field_addr(0, 0, 1);
        let yv = area.load(py, IrType::I32);
        let (_pv, ovf) = area.checked_bin(IrBin::Mul, IrType::I32, xv, yv);
        let _big = area.str_lit("big");
        let _small = area.str_lit("small");
        let zero = area.const_int(0);
        let ok = area.cmp(IrPred::Eq, IrType::Bool, ovf, zero);
        let (then_b, tb) = area.new_block("then");
        let (else_b, _eb) = area.new_block("else");
        let (cont_b, cb) = area.new_block("cont");
        area.cond_br(ok, &tb, &_eb.to_string());
        area.position(then_b);
        area.br(&cb);
        area.position(else_b);
        area.unreachable(); // オーバーフロー時は abort（簡略化）
        area.position(cont_b);
        area.ret(Some(xv));

        // make() -> Point (sret)
        let mut make = FnBuilder::new("_NGS_make".into(), vec![], IrType::Struct(0), true);
        let buf = make.alloca(IrType::Struct(0));
        let three = make.const_int(3);
        let seven = make.const_int(7);
        let fx = make.field_addr(buf, 0, 0);
        let fy = make.field_addr(buf, 0, 1);
        make.store(fx, three, IrType::I32);
        make.store(fy, seven, IrType::I32);
        make.ret(Some(buf));

        // main
        let mut main = FnBuilder::new("__NGS_main".into(), vec![], IrType::Void, false);
        let p = main.call("_NGS_make", vec![], IrType::Struct(0)).unwrap();
        let a = main.call("_NGS_area", vec![p], IrType::I32).unwrap();
        let ten = main.const_int(10);
        let gt = main.cmp(IrPred::Gt, IrType::I32, a, ten);
        let (bb, blab) = main.new_block("b1");
        let (eb, elab) = main.new_block("b2");
        let (jb, jlab) = main.new_block("join");
        main.cond_br(gt, &blab, &elab);
        main.position(bb);
        main.br(&jlab);
        main.position(eb);
        main.br(&jlab);
        main.position(jb);
        let msg = main.str_lit("done");
        let dp = main.addr_off(msg, 0);
        let lp = main.addr_off(msg, 8);
        let d = main.load(dp, IrType::Ptr(std::rc::Rc::new(IrType::U8)));
        let l = main.load(lp, IrType::Usize);
        main.call("__ngs_println_str", vec![d, l], IrType::Void);
        main.ret(None);

        let mut prog = IrProgram {
            structs,
            strings: vec![],
            main_name: Some("__NGS_main".into()),
            exports: vec![],
            enums: vec![],
            funcs: vec![],
        };
        // Const::Str(id) はグローバルプールのインデックスなので各ビルダに開始位置を教える
        let mut pool: Vec<String> = vec![];
        for mut fb in [area, make, main] {
            fb.set_strings_base(pool.len() as u32);
            pool.append(&mut fb.strings);
            prog.funcs.push(fb.func);
        }
        prog.strings = pool.into_iter().map(|s| ngs_ir::GlobalString { content: s }).collect();
        prog
    }
}
